version: '2.1'

services:
  dev:
    image: geo-mod
    build: .
    volumes:
      - ./src:/usr/src/program
    command: bash -c "
        g++ -o main main.cpp;
        ./main;
        rm main;
      "
  build:
    image: geo-mod
    build: .
    volumes:
      - ./src:/usr/src/program
    command: bash -c "
        mkdir -p ./build;
        g++ -o main main.cpp;
        mv main ./build/main;
      "