version: '3'

services:
  geo-c:
    image: 'gcc:4.9'
    volumes:
      - ./src:/home
      - ./build:/build
    user: root
    privileged: true
    command: >
      bash -c "
        rm -R -f /build/*;
        rm -R -f /build/**/*;
        mkdir /build;
        mkdir /build/compiled;
        make all --directory=/home;
        /build/geo_c;
      "